---
- name: Setup python python2 alternative
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python{{ python2_version }}
    priority: 1

- name: Setup python python3 alternative
  alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python{{ python3_version }}
    priority: 2

- name: Setup python3 python3 alternative
  alternatives:
    name: python3
    link: /usr/bin/python3
    path: /usr/bin/python{{ python3_version }}
    priority: 2

- name: Perform apt update
  apt:
    update_cache: yes

- name: Setup apt libraries for python, lirc, i2c, mpg123
  apt:
    pkg:
    - python3-apt
    - python3-pip
    - git
    - lirc
    - i2c-tools
    - python3-smbus
    - mpg123
    - python-alsaaudio
    state: present

- name: Install required pip packages
  pip:
    requirements: "{{ pi_home_folder }}/pi_radio/requirements.txt"

- name: Installing KY040 python package
  command: 
    chdir: "{{ pi_home_folder }}/pi_radio/KY040"
    cmd: "/usr/bin/python {{ pi_home_folder }}/pi_radio/KY040/setup.py install"

- name: Replacing wrong setup script block in lirc pip package
  replace:
    path: "{{ global_python3_dist_packages_folder }}/lirc/paths.py"
    regexp: "^os.unlink(os.path.join(HERE, '_client.so'))"
    replace: "# os.unlink(os.path.join(HERE, '_client.so'))"
