---
- hosts: all
  become: yes
  roles:
    - role: general_setup
      tags: general
    - role: python_setup
      tags: python
    - role: lirc_setup
      tags: lirc
    - role: swap_config
      tags: swap
  
  post_tasks:
    - name: Rebooting the RPi to apply all configurations
      reboot:
        reboot_timeout: 3600
      tags: reboot
