---
- name: Configure pi_radio
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - role: general_setup
      tags: general
    - role: python_setup
      tags: python
    - role: lirc_setup
      tags: lirc
    - role: swap_config
      tags: swap
  
  post_tasks:
    - name: Rebooting the RPi to apply all configurations
      reboot:
        reboot_timeout: 3600
      tags: reboot

    - name: Speaker test for initializing audio controls
      command: "speaker-test -D softvol -c2 -twav -l 2"
      tags: reboot
