---
- name: Copy config.txt
  copy:
    src: config.txt
    dest: /boot/config.txt
    owner: root
    group: root
    mode: 0750

- name: Add configs to /etc/modules
  blockinfile:
    path: /etc/modules
    block: |
      i2c-dev
      snd_soc_pcm5102a

- name: Copy and unzip pi_radio.zip
  unarchive:
    src: pi_radio.zip
    dest: "{{ pi_home_folder }}"
    remote_src: no

- name: Create log folder
  file:
    path: /home/pi/logs
    state: directory
    mode: 0750

- name: Configuring automatic startup for input_watcher.py script
  lineinfile:
    path: /etc/rc.local
    insertbefore: '^exit 0'
    line: "sudo python -B {{ pi_home_folder }}/pi_radio/input_watcher.py &"
